### ISSUE TITLE
Scrollbar in Rasberry Pi after 2.30 upgrade

### ISSUE THREAD

**Issue by jukkaforss** [Gulivertx/cbatmo#26]

**Comment by jukkaforss** [comment]
![E71DD0B8-1E8A-4627-BA0D-D219D2566AB2](https://user-images.githubusercontent.com/47186678/82151015-be3e2600-9849-11ea-8f98-c55c439bf609.jpeg)

**Comment by jukkaforss** [comment]
Seems that screen is bit bigger than 800x600 in 2.30 version.

**Comment by Gulivertx** [comment]
Will be fixed soon in version 2.3.1.

**Comment by karba71** [comment]
Hello,

since we have any rain today i have this fidget scrollbars on my screen.
I have V2.3.1 installed.

[20200602_194910_Trim.zip](https://github.com/Gulivertx/cbatmo/files/4719767/20200602_194910_Trim.zip)

**Comment by Gulivertx** [comment]
Ho damn ! The scrollbars appears only when Rain graph as some data to render ? When there was no Rain there is no scrollbar ?
Also, your app is really shaking or is it coming from the video ?

**Comment by jukkaforss** [comment]
Mine is acting same, really shaking with scrollbars. 


-Jukka-

Send from iPhone

**Comment by karba71** [comment]
Hello,

its really shaking.
And i think it comes from the rain.
If we have no rain then the data in 0 - 1 digit.
If we have rain or no data (NAN) then we have 3 digit (0,6 or NAN).
And then we have this scrollbars and shaking.

I use Chromium V 78.0.3904.108

![20200603_094222_resized](https://user-images.githubusercontent.com/56199098/83609929-2ea1b280-a57f-11ea-96bf-32d9b6c46449.jpg)

**Comment by jukkaforss** [comment]
I also use Chromium V 78.0.3904.108.
When this happening, if I killall chromium and restart it, it will be fine for awhile.
Here is video.
[IMG_7375.zip](https://github.com/Gulivertx/cbatmo/files/4721957/IMG_7375.zip)

**Comment by Gulivertx** [comment]
Ok thanks for your reports, I don’t have this trouble but I use webkit-gtk. 
I also see on your screenshots that the padding for lot of elements are not correct with chromium. I’m gonna investigate this...

**Comment by Gulivertx** [comment]
OK found the problem about the rain graph, the responsive chart is not re-render if the right values change. I will implement a render refresh of the graph each time the rain values change to force the graph re-render with the available width which should fix this shaking issue.

**Comment by tdostler** [comment]
> OK found the problem about the rain graph, the responsive chart is not re-render if the right values change. I will implement a render refresh of the graph each time the rain values change to force the graph re-render with the available width which should fix this shaking issue.

Can you explain, and give some hints, how to re-render the rain-graphic?

**Comment by Gulivertx** [comment]
@tdostler to force React to re-render any components there are different ways, the most common is to change a value in the component state or props. But there is also the ability to add a key to a component and by updating the key value React will re-render the component (not re-render for this case but unmount  and mount again the component), the last method is to use forceUpdate method (https://reactjs.org/docs/react-component.html#forceupdate).

I already tried to do it in the branch deploy_script, by adding a key on the graph component where the key has value of the rain module. So when the rain values change, the key of the graph get this new values, then the graph is unmount and mount again, but unfortunately it is not working, here is the change of my code : https://github.com/Gulivertx/cbatmo/commit/fc7beb8544d09d86e9f5a1833adb9783665c387c#diff-57f2be8e0124c6dfd7519e16ebadfed1R22-R28
I think I add the key id bad component because it's on the chart itself, which is re-render correctly but do not know his available width, I will try to re-render the parent component of the chart to see if it make any improvement...

**Comment by Gulivertx** [comment]
Damn it!!!!
Still shaking. I’m gonna make an update this weekend for I hope definitively suppress this issue. 
Related issue : https://github.com/Gulivertx/cbatmo/issues/41
Thank’s @karba71 for the report
